[package]
name = "jq-consumer-tests"
version = "0.0.0"
edition = "2024"
rust-version = "1.97"
publish = false

[features]
default = ["all", "std"]
all = ["jaq", "jq"]
std = ["jq/std", "serde_json/std"]
jaq = ["jq/jaq"]
jq = ["std", "jq/jq"]
arbitrary_precision = ["serde_json/arbitrary_precision"]
preserve_order = ["std", "serde_json/preserve_order"]

[dependencies]
jq = { path = "../..", default-features = false }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
