# See: https://docs.github.com/en/actions/writing-workflows
---
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  static-checks:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: Check documentation
        run: cargo doc --locked --workspace --all-features --no-deps
        env:
          RUSTDOCFLAGS: -D warnings
  build-ubuntu:
    name: Ubuntu (${{ matrix.rust }}, ${{ matrix.features.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.97.0", stable]
        features:
          - name: default
            args: ""
          - name: all
            args: --all-features
          - name: none
            args: --no-default-features
          - name: jaq
            args: --no-default-features --features jaq
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build
        run: cargo build --locked ${{ matrix.features.args }}
      - name: Build examples
        run: cargo build --locked --examples ${{ matrix.features.args }}
      - name: Run tests and doctests
        run: cargo test --locked ${{ matrix.features.args }}
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --locked
      - name: Build examples
        run: cargo build --locked --examples
      - name: Run tests
        run: cargo test --locked
